version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo

  prod-image:
    build: .
    ports:
      - 8082:8080
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: db-prod
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mongo